/**
 * Starway APIs
 * No description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AxiosRequestConfig } from 'axios';
import { axios } from '../axios.config';

import { CollectionsApi } from '../';

/* tslint:disable:no-unused-variable member-ordering max-line-length */

export class CollectionsApiResource {

    /**
     * Get single collection
     * description is absent
     */
    public getAllCollections(axiosConfig?: AxiosRequestConfig): Promise<Collections> {
        const reqPath = '/collections';
        let reqConfig = {
            ...axiosConfig,
            method: 'GET',
            url: reqPath
        };
        return axios.request(reqConfig)
            .then(res => {
                return res.data;
            });
    }

}

export const CollectionsApi = new CollectionsApiResource();
