/**
 * Starway APIs
 * No description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export interface Node {
    /**
     * Single node of knowledge
     */
    Node?: object;

    id: string;

    nodeType?: ;

    question: string;

    answer?: string;

}

export namespace Node {

}
